version: '3'
services:
  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis-data:/data'
    ports:
      - '6379:6379'

  guessit:
    image: guessit/guessit-rest
    ports:
      - '5000:80'

volumes:
  redis-data:
